### ISSUE TITLE
Value of a meta field is cut off at the first colon

### ISSUE THREAD

**Issue by denisobrienirl** [nospaceships/node-yara#13]
Hi Steve,

Another rather interesting finding. I noticed that a string value assigned to a meta ID gets cut off if there is a ':' character present. Here is what i got:
```
meta:
    source = "https://github.com/Neo23x0/signature-base/tree/master/yara"
```
and here is what i have in the output:

![image](https://user-images.githubusercontent.com/38887189/43543193-21ba39c6-95c7-11e8-9d3f-a0abf3c642d5.png)

Quite possible I'm doing something wrong here. Would appreciate you taking a look.

Cheers,

**Comment by stephenwvickers** [comment]
I saw this myself not so long ago while implementing my [Yaraka][yaraka] project but didn't get a chance to look into it.

I hope to take a look at this over the coming week.

[yaraka]: https://github.com/nospaceships/yaraka

**Comment by denisobrienirl** [comment]
Awesome! Thanks, Steve! Much appreciated!
